# rubocop version: 1.8.0

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# allow class A::B
Style/ClassAndModuleChildren:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 23

# allow method names with 'set_'
Naming/AccessorMethodName:
  Enabled: false

# allow 1-letter params (a, b, ...)
Naming/MethodParameterName:
  MinNameLength: 1
