# rubocop version: 1.8.0

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 160

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 22

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1